#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an RPM
#

# Pull base image
FROM opensuse/leap:15
MAINTAINER daos-stack <daos@daos.groups.io>

# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Add build user (to keep rpmbuild happy)
ENV USER build
RUN useradd -u $UID -ms /bin/bash $USER
RUN groupadd -g $UID $USER

# Install basic tools
RUN zypper --non-interactive update

# basic building
ENV RELVER="15.1"
ENV OPENSUSE_REPO="https://download.opensuse.org/repositories" \
    UPDATES_REPO="https://download.opensuse.org/update/leap/${RELVER}" \
    DIST_REPO="http://download.opensuse.org/distribution/leap/${RELVER}/repo"
ENV TOOLS_15A="openSUSE:/Tools/openSUSE_${RELVER}/openSUSE:Tools.repo"
ENV TOOLS_15="${OPENSUSE_REPO}/${TOOLS_15A}" \
    DIST_OSS_15="${DIST_REPO}/oss" \
    UPD_OSS_15="${UPDATES_REPO}/oss/openSUSE:Leap:${RELVER}:Update.repo"

# Build in repos have macros with $releasever not working for build,
# so need to be replaced.
# Two different syntax for ar depending on if the repository provides a .repo
RUN zypper --non-interactive mr --disable repo-update; \
    zypper --non-interactive mr --disable repo-oss; \
    zypper --non-interactive ar -f ${TOOLS_15}; \
    zypper --non-interactive ar -f ${DIST_OSS_15} distro-repo-oss; \
    zypper --non-interactive ar -f ${UPD_OSS_15}; \
    zypper --non-interactive --gpg-auto-import-keys refresh

RUN zypper --non-interactive --no-gpg-checks refresh; \
    zypper --non-interactive install autoconf automake build                  \
                                     ca-certificates-mozilla curl createrepo  \
                                     git libtool lsb-release make             \
                                     perl-libwww-perl perl-LWP-Protocol-https \
                                     perl-XML-Parser rpm-build sudo

# need to run the zypper and build command as root, as it needs to chroot
RUN echo "build ALL=(ALL) NOPASSWD: /usr/bin/build" > /etc/sudoers.d/build ; \
    echo "build ALL=(ALL) NOPASSWD: " \
    "/usr/bin/zypper --non-interactive --no-gpg-checks refresh" \
     >> /etc/sudoers.d/build; \
    chmod 0440 /etc/sudoers.d/build; \
    visudo -c; \
    sudo -l -U build
