#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an RPM
#

# Pull base image
FROM suse/sles:12.3
MAINTAINER daos-stack <daos@daos.groups.io>

# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Add build user (to keep rpmbuild happy)
ENV USER build
RUN useradd -u $UID -ms /bin/bash $USER
RUN groupadd -g $UID $USER

# Install basic tools
RUN zypper --non-interactive --no-gpg-checks refresh; \
    zypper --non-interactive update

# basic building
RUN zypper --non-interactive --no-gpg-checks refresh; \
    zypper --non-interactive install autoconf automake build                  \
                                     ca-certificates-mozilla curl createrepo  \
                                     git libtool lsb-release make             \
                                     perl-libwww-perl perl-LWP-Protocol-https \
                                     perl-XML-Parser rpm-build sudo

# need to run the zypper and build command as root, as it needs to chroot
RUN echo "#includedir /etc/sudoers.d" >> /etc/sudoers; \
    echo "build ALL=(ALL) NOPASSWD: /usr/bin/build" > /etc/sudoers.d/build ; \
    echo "build ALL=(ALL) NOPASSWD: " \
    "/usr/bin/zypper --non-interactive --no-gpg-checks refresh" \
     >> /etc/sudoers.d/build ; \
    chmod 0440 /etc/sudoers.d/build; \
    visudo -c; \
    sudo -l -U build
    

                             
#Temp patch until base docker image rebuilt
#Disable older SLES repositories.
RUN zypper --non-interactive mr --disable http-10.8.0.10-099eb6aa; \
    zypper --non-interactive mr --disable http-10.8.0.10-2a04a526; \
    zypper --non-interactive mr --disable http-10.8.0.10-33b60288; \
    zypper --non-interactive mr --disable http-10.8.0.10-4e00da6f; \
    zypper --non-interactive mr --disable http-10.8.0.10-82d67f5b; \
    zypper --non-interactive mr --disable http-10.8.0.10-ae069f46; \
    zypper --non-interactive mr --disable http-10.8.0.10-b2e5365a; \
    zypper --non-interactive mr --disable http-10.8.0.10-c059c690 || true

ENV OPENSUSE_REPO="https://download.opensuse.org/repositories"
ENV TOOLS_12_3A="openSUSE:/Tools/SLE_12_SP3/openSUSE:Tools.repo"
ENV TOOLS_12_3="${OPENSUSE_REPO}/${TOOLS_12_3A}"
ENV HPC_12_3A="science:/HPC:/SLE12SP3_Missing/SLE_12_SP3"
ENV HPC_12_3="${OPENSUSE_REPO}/${HPC_12_3A}/"
ENV HPC_42_3="${OPENSUSE_REPO}/science:/HPC/openSUSE_Leap_42.3"

# Two different syntax for ar depending on if the repository provides a .repo
RUN zypper --non-interactive ar -f ${TOOLS_12_3}; \
    zypper --non-interactive ar -f ${HPC_42_3}science:HPC.repo; \
    zypper --non-interactive ar -f ${HPC_12_3} Science_HPC_SLE_12_SP3; \
    zypper --non-interactive --gpg-auto-import-keys refresh

ARG JENKINS_URL=""
ENV JENKINS_PATH="${JENKINS_URL}job/daos-stack/job"
ENV JENKINS_ART="lastSuccessfulBuild/artifact/artifacts"
ARG MNGE_BRANCH="master"
RUN zypper --non-interactive ar --gpgcheck-allow-unsigned -f \
    ${JENKINS_PATH}/munge/job/${MNGE_BRANCH}/${JENKINS_ART}/sles12.3/ munge; \
    zypper --non-interactive ref munge

# These repositories can only be used by suse build if passed with a repo
# command.
RUN echo " --repo ${HPC_42_3}" \
    "--repo http://cobbler/cobbler/repo_mirror/updates-sles12.3-x86_64" \
    "--repo http://cobbler/cobbler/repo_mirror/sdkupdate-sles12.3-x86_64" \
    "--repo http://cobbler/cobbler/repo_mirror/sdk-sles12.3-x86_64" > \
    /tmp/build.repos
